version: '{build}'
skip_tags: true
image: Visual Studio 2019
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Serilog.Sinks.BrowserConsole.*.nupkg;artifacts/Serilog.AspNetCore.Ingestion.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: /Dm+EI0E1vCa+rZfYkluSnk7iSnAFKNOcEpreQrG88uYqCm//dKpY5vwqb1EJm3j
  on:
    branch: /^(master|dev)$/

