version: '{build}'
skip_tags: true
image: Visual Studio 2019
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Serilog.Sinks.BrowserHttp.*.nupkg;artifacts/Serilog.AspNetCore.Ingestion.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: O3jq5SA3ebcA2GXDNxGZ69EwRXqUGzxRgASh4Hr5FWAqsXcWIbiDM0kTpenu4QrT
  on:
    branch: /^(master|dev)$/

